config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  mount Sidekiq::Web => '/sidekiq'

  root 'welcome#index'

  devise_for :users,
             controllers: { sessions: 'sessions', registrations: 'registrations' }

  resources :auth, only: [] do
    collection do
      post :register,    action: :register
      post :login,       action: :login
      post :check_email, action: :check_email
    end
  end

  resources :profile_builder, only: %i[index show update], path: 'build_services'

  resources :profile, only: %i[show] do
    collection do
      get :manage_availability, as: :availability
      get :manage_bookings, as: :bookings
      get :messages
    end
  end

  resources :users, only: %i[update] do
    collection do
      get :profile
      get 'edit/login', to: 'users#edit_login'
      get 'edit/profile', to: 'users#edit_profile'
      get :images
      post :create_images
      delete 'delete_images/:id', action: :delete_images
    end
  end

  resources :search, only: %i[index]
end

app/views/shared/header/_header.haml
%nav.navbar.navbar-expand-lg.fixed-top.navbar-big-padding{ class: landing_header }
  .container
    .navbar-inner
      %button.navbar-toggler.collapsable-button.collapsed{ aria: {controls: 'collapsable-nav-content', expanded: 'false', label: 'Toggle navigation'}, data: { target: '#collapsable-nav-content', toggle: 'collapse' }, type: 'button'}
        .animated-icon
          %span
          %span
          %span

      = link_to root_path, class: 'navbar-brand mr-auto mobile-logo' do
        = image_tag("#{asset_pack_path('media/img/mobile-logo.png')}")

    .collapse.navbar-collapse#collapsable-nav-content
      .navbar-logo
        = link_to root_path, class: 'navbar-brand' do
          = image_tag("#{asset_pack_path('media/img/bjj-logo.png')}")
      %ul.navbar-nav.ml-auto.mt-2.mt-lg-0.align-items-center
        - if current_user&.admin?
          %li.nav-item
            = link_to 'Admin Panel', admins_dashboard_path, class: 'nav-link nobreak'
        %li.nav-item
          = link_to t('.nav.find_someone'), search_index_path, class: 'nav-link nobreak'

        - unless current_user&.customer?
          %li.nav-item
            = link_to t('.nav.ofer_training'), profile_builder_index_path, class: 'nav-link nobreak'

        %li.nav-item
          = sign_up_or_navigate_to(t('.nav.bookings'), bookings_profile_index_path)

        - if current_user&.merchant?
          %li.nav-item
            = link_to t('.nav.availability'), availability_profile_index_path, class: 'nav-link click-mod'

        %li.nav-item
          = sign_up_or_navigate_to(t('.nav.messages'), messages_profile_index_path)

        - if user_signed_in?
          %li.nav-item
            = link_to 'Profile', profile_users_path, class: 'nav-link nobreak'

        %li.nav-item
          = sign_up_or_navigate_to('Sign out', destroy_user_session_path, method: :delete)