config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  mount Sidekiq::Web => '/sidekiq'

  root 'welcome#index'

  devise_for :users,
             controllers: { sessions: 'sessions', registrations: 'registrations' }

  resources :auth, only: [] do
    collection do
      post :register,    action: :register
      post :login,       action: :login
      post :check_email, action: :check_email
    end
  end

  resources :profile_builder, only: %i[index show update], path: 'build_services'

  resources :profile, only: %i[show] do
    collection do
      get :manage_availability, as: :availability
      get :manage_bookings, as: :bookings
      get :messages
    end
  end

  resources :users, only: %i[update] do
    collection do
      get :profile
      get 'edit/login', to: 'users#edit_login'
      get 'edit/profile', to: 'users#edit_profile'
      get :images
      post :create_images
      delete 'delete_images/:id', action: :delete_images
    end
  end

  resources :search, only: %i[index]
end

app/controllers/profile_builder_controller.rb
class ProfileBuilderController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :verify_wizard_step, only: :show

  include Wicked::Wizard

  steps :gym_location, :listing_name, :pricing, :specializations, :images, :services_offered,
        :rules, :cancellations, :payments

  def index; end

  def show
    init_form_and_authorize!

    render_wizard
  end

  def update
    init_form_and_authorize!

    if @wizard_form.submit(params[:user])
      redirect_to wizard_path(next_step)
    else
      render_step(step)
    end
  end

  # After all steps is completed
  def finish_wizard_path
    current_user.update(wizard_complete: true)
    availability_profile_index_path
  end

  private

  def verify_wizard_step
    return redirect_to finish_wizard_path if params[:id].eql?('wicked_finish')

    redirect_to wizard_path(:gym_location) unless wizard_steps.include?(params[:id].to_sym)
  end

  def init_form_and_authorize!
    @wizard_form ||= Users::Forms::Builder.for(step, current_user)

    authorize! @wizard_form, to: :show?, with: ProfileBuilderPolicy
  end
end

app/views/profile_builder/_errors.haml
= content_tag :div, class: 'resource-errors' do
  %h2 #{pluralize(resource.errors.count, 'error')} detected!
  %ul
    - resource.errors.full_messages.each do |msg|
      %li= msg

app/views/profile_builder/_steps_tabs.haml
- steps = ['Gym location', 'Listing Name', 'Pricing', 'Your Specializations', 'Image', 'Services Offered', 'Rules', 'Cancellation', 'Payment Method']
- current_index = steps.index(active_step)

.profile-builder-tabs.hide-on-mobile
  - steps.each_with_index do |step, index|
    - passed_class = current_index > index ? 'passed' : ''
    - active_class = current_index == index ? 'active' : ''

    = content_tag :div, step, class: "profile-builder-tabs-item #{passed_class} #{active_class}"

%select.select-field.tab-header.hide-on-desktop{name: 'select'}
  %option{value: 'value1'} Gym location
  %option{value: 'value2'} Listing Name
  %option{value: 'value3'} Pricing
  %option{value: 'value4'} Your Specializations
  %option{value: 'value5'} Services Offered
  %option{value: 'value6'} Rules
  %option{value: 'value7'} Cancellation
  %option{value: 'value8'} Payment Method

app/views/profile_builder/cancellations.haml
= render partial: 'shared/sub_header/sub_header', locals: { header_title: 'Configure You Profile', btn_text: '', btn_url: nil }


.profile-builder-cancellation
  .container
    = render partial: 'steps_tabs', locals: { active_step: 'Cancellation' }

    .profile-builder-block-title
      %h2 Cancellation Policy
      %p Choose among three cancellation policies

    = form_with model: @wizard_form, url: wizard_path, scope: :user, method: :put, local: true, html: { class: 'profile-builder-form' } do |f|
      - if @wizard_form.errors.any?
        = render 'errors', resource: @wizard_form

      .profile-builder-form-row.row
        .profile-builder-field-block.col-md-6
          - User::CANCELLATION.each do |item|
            .cancellation-block
              = f.label "cancellations_#{to_snake_case(item)}", class: 'checkbox-block' do
                %span.label-title= item
                %span.label-text Student may cancel up to 3 hours before the session
                = f.check_box :cancellations, { multiple: true, checked: @wizard_form.send(to_snake_case(item)).present? }, item, false
                %span.checkmark
      .profile-builder-form-footer
        = link_to 'Back', previous_wizard_path, class: 'btn btn-no-bg-no-bordered'
        = f.submit 'Next', class: 'btn btn-primary ml-auto'

app/views/profile_builder/gym_location.haml
= render partial: 'shared/sub_header/sub_header', locals: { header_title: 'Configure You Profile', btn_text: '', btn_url: nil }

.profile-builder-gym-location
  .container
    = render partial: 'steps_tabs', locals: { active_step: 'Gym location' }



    = form_with model: @wizard_form, url: wizard_path, scope: :user, method: :put, local: true, html: { class: 'profile-builder-form' } do |f|
      - if @wizard_form.errors.any?
        = render 'errors', resource: @wizard_form

      .profile-builder-block-checkbox
        %label.checkbox-block
          Offer privates at customer’s location
          %em (you go to them)
          %input{:type => "checkbox"}/
          %span.checkmark

        %label.checkbox-block
          Offer privates at your gym or other location
          %em (they come to you)
          %input{:type => "checkbox"}/
          %span.checkmark


      .profile-builder-block-title
        %h2 Where is your Gym located?

      .profile-builder-field-block
        = f.label :gym_address, 'Enter Address'
        = f.text_field :gym_address, class: 'inpute-field'

      .profile-builder-field-block.mt-20
        = f.label :gym_instructions, 'Special Instructions'
        = f.text_area :gym_instructions, placeholder: 'e.g. come up to the front door', class: 'textarea-field'

      .profile-builder-form-bottom-text Address will only be show to confirmed users.
      .profile-builder-form-footer
        = f.submit 'Next', class: 'btn btn-primary ml-auto'

app/views/profile_builder/images.haml
= render partial: 'shared/sub_header/sub_header', locals: { header_title: 'Configure You Profile', btn_text: '', btn_url: nil }


.profile-builder-images
  .container
    = render partial: 'steps_tabs', locals: { active_step: 'Image' }

    .profile-builder-block-title
      %h2 Upload Images
      %p Showcase your best photos! You can always upload photos later or email us!
    %merchant-images-form{'inline-template': ''}
      .profile-builder-upload
        .profile-builder-upload-top-text Cover Photo Upload
        .profile-builder-upload-current-image{'v-for': "(object, key) in images", ':id': "'image-id-' + object.id"}
          %img{':src': "object.image.url" }
          %i.fa.fa-trash{'@click': "removeImage(object.id)"}

        = form_with url: create_images_users_path, html: { id: 'merchant-images-form' } do |f|
          = f.file_field :images, multiple: true, id: 'merchant-images-form-input', '@change': "handleFileUploads"

        .profile-builder-upload-additional
          .profile-builder-upload-additional-title Upload additional photos
          .profile-builder-upload-additional-subtitle Add upto 9 additional photo
          .profile-builder-upload-additional-plus{id: 'merchant-images-form-btn', '@click': "addFiles"}
            %span +

        .profile-builder-form-footer
          = link_to 'Back', previous_wizard_path, class: 'btn btn-no-bg-no-bordered'
          = link_to 'Next', next_wizard_path, class: 'btn btn-primary ml-auto'

app/views/profile_builder/index.haml
.profile-builder-start
  .container
    .profile-builder-start-top-block
      %h1.start-title Offer your Grappling Services
      %h6.start-subtitle Earn extra income by sharing your knowledge!

    .profile-builder-start-list
      %div
        .icon-wr
          = image_tag("#{asset_pack_path('media/img/search.svg')}")
        %span List
      %div
        .icon-wr
          = image_tag("#{asset_pack_path('media/img/credit-card.svg')}")
        %span Set Prices and Calendar
      %div
        .icon-wr
          = image_tag("#{asset_pack_path('media/img/calendar.svg')}", width: 34)
        %span Take Reservations
      %div
        .icon-wr
          = image_tag("#{asset_pack_path('media/img/money.svg')}")
        %span Get Paid for Sessions

    %p.start-list-detail-text Once you've added your services, we'll verify your rank and credentials to certify you for FREE before listing you on the site.
    - if current_user&.merchant?
      = link_to 'Get Started', wizard_path(:gym_location), class: 'btn btn-primary ml-auto'
    - else
      = link_to 'Get Started', '#', data: {target: '#sign-up-modal', toggle: 'modal'}, class: 'btn btn-primary ml-auto'

app/views/profile_builder/listing_name.haml
= render partial: 'shared/sub_header/sub_header', locals: { header_title: 'Configure You Profile', btn_text: '', btn_url: nil }

.profile-builder-listing-name
  .container
    = render partial: 'steps_tabs', locals: { active_step: 'Listing Name' }

    .profile-builder-block-title
      %h2 Listing Name & Description
      %p Give a creative name and description to help it stand out in search results.

    = form_with model: @wizard_form, url: wizard_path, scope: :user, method: :put, local: true, html: { class: 'profile-builder-form' } do |f|
      - if @wizard_form.errors.any?
        = render 'errors', resource: @wizard_form

      .profile-builder-field-block
        = f.label :listing_name
        = f.text_field :listing_name, placeholder: 'e.g. best leglocker in the world', class: 'inpute-field'
      .profile-builder-field-block.mt-20
        %label
          Describe your services
          %em (This is your sales pitch)
        = f.text_area :listing_description, placeholder: 'e.g. I’ll take your leglock game to the next level.', class: 'textarea-field'
      .profile-builder-form-footer
        = link_to 'Back', previous_wizard_path, class: 'btn btn-no-bg-no-bordered'
        = f.submit 'Next', class: 'btn btn-primary ml-auto'

app/views/profile_builder/payments.haml
= render partial: 'shared/sub_header/sub_header', locals: { header_title: 'Configure You Profile', btn_text: '', btn_url: nil }

.profile-builder-payment
  .container
    = render partial: 'steps_tabs', locals: { active_step: 'Payment Method' }

    .profile-builder-block-title
      %h2 Setup Your Payment Method
      %p Securely connect your debt card or bank account via Stripe to receive payouts. Payouts are sent 24 hours after a successful booking.

    %button.btn.btn-primary-no-bg Connect your account
    .payment-list
      %p You will be asked for the following (it only takes a minute)
      %p 1/ &nbsp;&nbsp; Your email address and phone number.
      %p 2/ &nbsp;&nbsp; Your full legal name and “business site link” (just enter bookbjj.com for that).
      %p 3/ &nbsp;&nbsp; A bank account or debit card for us to send your funds to.

    .profile-builder-form-footer
      = link_to 'Back', previous_wizard_path, class: 'btn btn-no-bg-no-bordered'
      = link_to 'Next', wizard_path(:wicked_finish), class: 'btn btn-primary ml-auto'

app/views/profile_builder/pricing.haml
= render partial: 'shared/sub_header/sub_header', locals: { header_title: 'Configure You Profile', btn_text: '', btn_url: nil }

.profile-builder-pricing
  .container
    = render partial: 'steps_tabs', locals: { active_step: 'Pricing' }

    .profile-builder-block-title
      %h2 Pricing
      %p How much do you charge and who can come?

    = form_with model: @wizard_form, url: wizard_path, scope: :user, method: :put, local: true, html: { class: 'profile-builder-form' } do |f|
      - if @wizard_form.errors.any?
        = render 'errors', resource: @wizard_form

      .profile-builder-form-row.row
        .profile-builder-field-block.col-md-4
          = f.label :hourly_rate do
            Hourly Rate
            %em (per hour)
          = f.select :hourly_rate, options_for_select([['$70', '70'], ['$80', '80'], ['$90', '90'], ['$100', '100']], @wizard_form.hourly_rate), {}, class: 'select-field'
        .profile-builder-field-block.col-md-4
          = f.label :number_people, 'Minimum Number of People'
          = f.select :number_people, options_for_select([['1', '1'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5']],  @wizard_form.number_people), {}, class: 'select-field'

      .profile-builder-field-block.mt-30
        = f.label :filming_allowed, 'Filming Allowed?'
        .radio-toolbar
          = f.radio_button :filming_allowed, true, checked: true, id: 'allowed-yes'
          %label{for: 'allowed-yes'} Yes
          = f.radio_button :filming_allowed, false, id: 'allowed-no'
          %label{for: 'allowed-no'} No
      .profile-builder-form-footer
        = link_to 'back', previous_wizard_path, class: 'btn btn-no-bg-no-bordered'
        = f.submit 'Next', class: 'btn btn-primary ml-auto'

app/views/profile_builder/rules.haml
= render partial: 'shared/sub_header/sub_header', locals: { header_title: 'Configure You Profile', btn_text: '', btn_url: nil }


.profile-builder-rules
  .container
    = render partial: 'steps_tabs', locals: { active_step: 'Rules' }

    .profile-builder-block-title
      %h2 Rules
      %p Select all the following that apply


    = form_with model: @wizard_form, url: wizard_path, scope: :user, method: :put, local: true, html: { class: 'profile-builder-form' } do |f|
      - if @wizard_form.errors.any?
        = render 'errors', resource: @wizard_form

      .profile-builder-form-row.row
        - User::RULES.each do |item|
          .profile-builder-field-block.col-md-4
            = f.label "rules_apply_#{to_snake_case(item)}", class: 'checkbox-block' do
              #{item}
              = f.check_box :rules_apply, { multiple: true, checked: @wizard_form.send(to_snake_case(item)).present? }, item, false
              %span.checkmark

      .profile-builder-field-block.mt-20.range-block
        %div Travel
        .grey-text I will travel upto:

        .range-block
          .range-slider
            %span#rs-bullet.rs-label 0
            #range-fill.range-fill
            = f.range_field :rules_travel, max: '2', min: '0', step: '0.5', id: 'rs-range-line', class: 'rs-range'
          .box-minmax
            %div
              %span 0
            %div
              %span 30MIN
            %div
              %span 1 HOUR
            %div
              %span 1HOUR30MIN
            %div
              %span 2HOUR

      .profile-builder-field-block.mt-20
        = f.label :rules_additional, 'Additional Rules'
        = f.text_area :rules_additional, placeholder: 'e.g. please warm up before your session', class: 'textarea-field'

      .profile-builder-form-footer
        = link_to 'Back', previous_wizard_path, class: 'btn btn-no-bg-no-bordered'
        = f.submit 'Next', class: 'btn btn-primary ml-auto'

app/views/profile_builder/services_offered.haml
= render partial: 'shared/sub_header/sub_header', locals: { header_title: 'Configure You Profile', btn_text: '', btn_url: nil }

.profile-builder-service-offered
  .container
    = render partial: 'steps_tabs', locals: { active_step: 'Services Offered' }

    .profile-builder-block-title
      %h2 Services You Offer
      %p You must offer a general per hour private rate, but can also offer a variety of other specialized services


    = form_with model: @wizard_form, url: wizard_path, scope: :user, method: :put, local: true, html: { class: 'profile-builder-form' } do |f|
      - if @wizard_form.errors.any?
        = render 'errors', resource: @wizard_form
      .profile-builder-form-row
        .profile-builder-field-block
          = f.label :services_private_session do
            General Private Session
            %em (per hour)
          = f.select :services_private_session, options_for_select([['$100', '100'], ['$200', '200'], ['$300', '300'], ['$400', '400']], @wizard_form.services_private_session), {}, class: 'select-field'

          = f.label :services_roll_review do
            Roll Reviews
            %em (per hour)
          = f.select :services_roll_review, options_for_select([['$50', '50'], ['$60', '60'], ['$70', '70'], ['$80', '80'], ['$90', '90']],  @wizard_form.services_roll_review), {}, class: 'select-field'

          = f.label :services_skype_call do
            Skype Call
            %em (per hour)
          = f.select :services_skype_call, options_for_select([['$10', '10'], ['$20', '20'], ['$30', '30'], ['$40', '40'], ['$50', '50']],  @wizard_form.services_skype_call), {}, class: 'select-field'

          = f.label :services_seminar do
            Seminar
            %em (per hour)
          = f.select :services_seminar, options_for_select([['$1000', '1000'], ['$2000', '2000'], ['$3000', '3000']],  @wizard_form.services_seminar), {}, class: 'select-field'
      .profile-builder-form-footer
        = link_to 'Back', previous_wizard_path, class: 'btn btn-no-bg-no-bordered'
        = f.submit 'Next', class: 'btn btn-primary ml-auto'

app/views/profile_builder/specializations.haml
= render partial: 'shared/sub_header/sub_header', locals: { header_title: 'Configure You Profile', btn_text: '', btn_url: nil }


.profile-builder-specialization
  .container
    = render partial: 'steps_tabs', locals: { active_step: 'Your Specializations' }

    .profile-builder-block-title
      %h2 What do you specialize in?
      %p Select all the following that apply

    = form_with model: @wizard_form, url: wizard_path, scope: :user, method: :put, local: true, html: { class: 'profile-builder-form' } do |f|
      - if @wizard_form.errors.any?
        = render 'errors', resource: @wizard_form

      .profile-builder-form-row.row
        .profile-builder-field-block.col-md-4
          = f.label 'specializations_gi', class: 'checkbox-block' do
            Gi
            = f.check_box :specializations, { multiple: true, checked: @wizard_form.gi.present? }, 'Gi', false
            %span.checkmark
          = f.label 'specializations_kimura', class: 'checkbox-block' do
            Kimura
            = f.check_box :specializations, { multiple: true, checked: @wizard_form.kimura.present? }, 'Kimura', false
            %span.checkmark

          = f.label 'specializations_armbars', class: 'checkbox-block' do
            Armbars
            = f.check_box :specializations, { multiple: true, checked: @wizard_form.armbars.present? }, 'Armbars', false
            %span.checkmark

          = f.label 'specializations_front_headlock', class: 'checkbox-block' do
            Front Headlock
            = f.check_box :specializations, { multiple: true, checked: @wizard_form.front_headlock.present? }, 'Front Headlock', false
            %span.checkmark

        .profile-builder-field-block.col-md-4
          = f.label 'specializations_smash_punching', class: 'checkbox-block' do
            Smash Punching
            = f.check_box :specializations, { multiple: true, checked: @wizard_form.smash_punching.present? }, 'Smash Punching', false
            %span.checkmark

          = f.label 'specializations_no_gi', class: 'checkbox-block' do
            No Gi
            = f.check_box :specializations, { multiple: true, checked: @wizard_form.no_gi.present? }, 'No Gi', false
            %span.checkmark

          = f.label 'specializations_rubber_guard', class: 'checkbox-block' do
            Rubber Guard
            = f.check_box :specializations, { multiple: true, checked: @wizard_form.rubber_guard.present? }, 'Rubber Guard', false
            %span.checkmark

          = f.label 'specializations_peruvian_necktie', class: 'checkbox-block' do
            Peruvian Necktie
            = f.check_box :specializations, { multiple: true, checked: @wizard_form.peruvian_necktie.present? }, 'Peruvian Necktie', false
            %span.checkmark

        .profile-builder-field-block.col-md-4
          = f.label 'specializations_leglocks', class: 'checkbox-block' do
            Leglocks
            = f.check_box :specializations, { multiple: true, checked: @wizard_form.leglocks.present? }, 'Leglocks', false
            %span.checkmark
          = f.label 'specializations_full_guard', class: 'checkbox-block' do
            Full Guard
            = f.check_box :specializations, { multiple: true, checked: @wizard_form.full_guard.present? }, 'Full Guard', false
            %span.checkmark

          = f.label 'specializations_kneebars', class: 'checkbox-block' do
            Kneebars
            = f.check_box :specializations, { multiple: true, checked: @wizard_form.kneebars.present? }, 'Kneebars', false
            %span.checkmark

      .profile-builder-form-footer
        = link_to 'Back', previous_wizard_path, class: 'btn btn-no-bg-no-bordered'
        = f.submit 'Next', class: 'btn btn-primary ml-auto'