config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  mount Sidekiq::Web => '/sidekiq'

  root 'welcome#index'

  devise_for :users,
             controllers: { sessions: 'sessions', registrations: 'registrations' }

  resources :auth, only: [] do
    collection do
      post :register,    action: :register
      post :login,       action: :login
      post :check_email, action: :check_email
    end
  end

  resources :profile_builder, only: %i[index show update], path: 'build_services'

  resources :profile, only: %i[show] do
    collection do
      get :manage_availability, as: :availability
      get :manage_bookings, as: :bookings
      get :messages
    end
  end

  resources :users, only: %i[update] do
    collection do
      get :profile
      get 'edit/login', to: 'users#edit_login'
      get 'edit/profile', to: 'users#edit_profile'
      get :images
      post :create_images
      delete 'delete_images/:id', action: :delete_images
    end
  end

  resources :search, only: %i[index]
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    collection = Merchant.with_data.all # just for stub

    render_template!('index', merchants: MerchantDecorator.decorate_collection(collection))
  end
end

app/views/search/index/index.haml
.search-filter
  .container

    .search-toggle-block.hide-on-desktop
      %p Search Filters
      .search-open +

    .search-filter-data.row
      .col-md-3.col-sm-12
        .profile-builder-field-block.field-with-icon
          %i.fa.fa-search
          %input.inpute-field{:placeholder => "Great Neck, NY, USA", :type => "text"}/
      .col-md-2.col-sm-6
        .profile-builder-field-block.field-with-icon
          %i.fa.fa-clock-o
          %input.inpute-field{:placeholder => "Date", :type => "text"}/
      .col-md-2.col-sm-6
        .profile-builder-field-block.field-with-icon
          %i.fa.fa-calendar
          %input.inpute-field{:placeholder => "Time", :type => "text"}/
      .col-md-2.col-sm-12
        .profile-builder-field-block.field-with-icon
          %select.select-field{:name => "select"}
            %option{:value => "value1"} Gym location
      .col-md-3.col-sm-12
        .custom-dropdown
          .custom-dropdown-title Speciality
          .custom-dropdown-content
            %input.custom-dropdown-input{:placeholder => "Filter", :type => "text"}/
            .custom-dropdown-list
              .profile-builder-field-block
                %label.checkbox-block
                  Front headlock
                  %input{:type => "checkbox"}/
                  %span.checkmark
              .profile-builder-field-block
                %label.checkbox-block
                  Front headlock
                  %input{:type => "checkbox"}/
                  %span.checkmark
              .profile-builder-field-block
                %label.checkbox-block
                  Front headlock
                  %input{:type => "checkbox"}/
                  %span.checkmark
              .profile-builder-field-block
                %label.checkbox-block
                  Front headlock
                  %input{:type => "checkbox"}/
                  %span.checkmark
              .profile-builder-field-block
                %label.checkbox-block
                  Front headlock
                  %input{:type => "checkbox"}/
                  %span.checkmark
              .profile-builder-field-block
                %label.checkbox-block
                  Front headlock
                  %input{:type => "checkbox"}/
                  %span.checkmark
              .profile-builder-field-block
                %label.checkbox-block
                  Front headlock
                  %input{:type => "checkbox"}/
                  %span.checkmark
              .profile-builder-field-block
                %label.checkbox-block
                  Front headlock
                  %input{:type => "checkbox"}/
                  %span.checkmark

    .search-filter-action
      %button.btn.btn-primary Search

      .profile-builder-field-block
        %label.checkbox-block
          = image_tag("#{asset_pack_path('media/img/stopwatch.svg')}")
          %span.text Instant Booking
          %input{:type => "checkbox"}/
          %span.checkmark



.search-details
  .container
    .search-details-count 56 Instructors
    %select.select-field.no-bg{:name => "select"}
      %option{:value => "value1"} Miles
      %option{:value => "value2"} Km

%section.trainers-card
  .container
    .trainers-card-body
      .row
        - merchants.each do |merchant|
          .col-12.col-lg-6.mb-4
            .card.flex-row.merchant-card
              .card-header.border-0.p-0
                .merchant-avatar
                  = image_tag(merchant.avatar.url)
                  .belt.black Black belt
              .card-body
                .merchant-wrapper.h-100.d-flex.flex-column
                  .merchant-name
                    .name.mr-1
                      = merchant.full_name
                    .price-per.ml-auto.d-flex.flex-row
                      %span.price= merchant.hourly_rate
                      %span.per /hr

                  .merchant-location Miami, Florida, 33138
                  .merchant-range 4.1 miles
                  .rating.mt-auto
                    .stars
                      %span.stars-sym &#11089;&#11089;&#11089;&#11089;&#11089;
                      %span.rate 9.7
                    = link_to 'View profile', profile_path(merchant), class: 'btn btn-primary ml-auto'

app/views/search/index/trainers_card.haml
.col-12.col-lg-6.mb-4
  .card.flex-row.merchant-card
    .card-header.border-0.p-0
      .merchant-avatar
        %img{:alt => "", :src => "https://api.adorable.io/avatars/160/abott@adorable.png"}
        .belt.black Black belt
    .card-body
      .merchant-wrapper.h-100.d-flex.flex-column
        .merchant-name
          .name.mr-1
            Josdsdsn Doesdsds sdsdsdd
          .price-per.ml-auto.d-flex.flex-row
            %span.price $40
            %span.per /hr

        .merchant-location Miami, Florida, 33138
        .merchant-range 4.1 miles
        .rating.mt-auto
          .stars
            %span.stars-sym &#11089;&#11089;&#11089;&#11089;&#11089;
            %span.rate 9.7
          %button.btn.btn-primary.ml-auto View profile