config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do

  ActiveAdmin.routes(self)
  mount Sidekiq::Web => '/sidekiq'

  root 'welcome#index'

  devise_for :users,
             controllers: { sessions: 'sessions', registrations: 'registrations' }

  resources :auth, only: [] do
    collection do
      post :register,    action: :register
      post :login,       action: :login
      post :check_email, action: :check_email
    end
  end

  resources :profile_builder, only: %i[index show update], path: 'build_services'

  resources :profile, only: %i[show] do
    collection do
      get :manage_availability, as: :availability
      get :manage_bookings, as: :bookings
      get :messages
    end
  end

  resources :users, only: %i[update] do
    collection do
      get :profile
      get 'edit/login', to: 'users#edit_login'
      get 'edit/profile', to: 'users#edit_profile'
      get :images
      post :create_images
      delete 'delete_images/:id', action: :delete_images
    end
  end

  resources :search, only: %i[index]
end

app/views/shared/modals/booking/_booking.haml
#exampleModal.modal.fade.modal-request-booking{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      = form_with url: login_auth_index_path, html: { id: 'qwerty' } do |f|
        -# .form-group
        -#   = f.label :date
        -#   = f.text_field :date, class: 'form-control'
        -#
        -# .form-group
        -#   = f.label :time
        -#   = f.text_field :time, class: 'form-control'
        -#
        -#
        -#
        -# = f.submit 'Login', class: 'btn btn-primary'

      .request-booking
        .request-booking-header
          .request-booking-header-title Request Booking
          %button.btn.btn-primary Book Now
          .request-booking-header-close
            %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
              %span{"aria-hidden" => "true"} ×

        .request-booking-form
          .label Session Date and Time
          .request-booking-form-line
            .profile-builder-field-block.field-with-icon
              %i.fa.fa-calendar
              %input.inpute-field{:placeholder => "July 22, 2019", :type => "text"}/

            .profile-builder-field-block.field-with-icon
              %i.fa.fa-clock-o
              %input.inpute-field{:placeholder => "3:00 PM - 7:00 PM", :type => "text"}/

          .label People
          .profile-builder-field-block.field-with-icon
            %select.select-field{:name => "select"}
              %option{:value => "value1"} 1 Adult
          .label Booking Type
          .profile-builder-field-block.field-with-icon
            %select.select-field{:name => "select"}
              %option{:value => "value1"} Private at your house

          .payment-details
            .payment-details-title  Payment Details
            .payment-details-text Once we approve your request, you will be asked to confirm it, only then you will be charged!
            .payment-details-table
              .payment-details-table-line
                .payment-details-table-line-name $75 x 4.0 hours
                .payment-details-table-line-count $300.00
              .payment-details-table-line
                .payment-details-table-line-name Service fee
                .payment-details-table-line-count $30.00
              .payment-details-table-total
                .payment-details-table-total-text TOTAL
                .payment-details-table-total-value $330.00

          .payment-method
            .payment-method-title  Payment Details
            .payment-method-buttons
              %button.payment-btn
                %i.fa.fa-credit-card-alt
                %span Credit Card
              %button.payment-btn.active
                %i.fa.fa-paypal
                %span PayPal

            .payment-method-form
              .payment-method-form-inner
                .label Your PayPal Email Address
                .request-booking-form-line
                  %input.inpute-field{:placeholder => "", :type => "text"}/
              .payment-method-form-inner
                .label Card Number
                .request-booking-form-line
                  %input.inpute-field{:placeholder => "", :type => "text"}/
                .label Card Holder
                .request-booking-form-line
                  %input.inpute-field{:placeholder => "", :type => "text"}/
                .payment-method-form-inner-columns
                  %div
                    .label Card Holder
                    .request-booking-form-line
                      %input.inpute-field{:placeholder => "05", :type => "text"}/
                  %div
                    .label Exp. Year
                    .request-booking-form-line
                      %input.inpute-field{:placeholder => "2023", :type => "text"}/
                  %div
                    .label CVC
                    .request-booking-form-line
                      %input.inpute-field{:placeholder => "****", :type => "text"}/